// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MenuList struct {
	MenuID   string `json:"menu_id"`
	Name     string `json:"name"`
	Price    int    `json:"price"`
	TypeName string `json:"type_name"`
	WartegID string `json:"warteg_id"`
}
